desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: HEAT_DB_PASSWORD
        value: heatdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-heat-engine
      name: heat-engine
      ports:
      - containerPort: 9292
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: HEAT_DB_PASSWORD
        value: heatdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-heat-api
      name: heat-api
      ports:
      - containerPort: 9292
    id: heat-1
    version: v1beta1
id: heat
labels:
  name: keystone-master
