desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      image: kollaglue/fedora-rdo-mariadb
      name: mariadb
      ports:
      - containerPort: 3306
    id: mariadb-1
    version: v1beta1
id: mariadb
labels:
  name: mariadb
