desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: SWIFT_DB_PASSWORD
        value: swiftdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-swift-account-server
      name: swift-account-server
      ports:
      - containerPort: 9292
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: SWIFT_DB_PASSWORD
        value: swiftdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-swift-container-server
      name: swift-container-server
      ports:
      - containerPort: 9292
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: SWIFT_DB_PASSWORD
        value: swiftdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-swift-object-server
      name: swift-object-server
      ports:
      - containerPort: 9292
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: SWIFT_DB_PASSWORD
        value: swiftdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: fedora-rdo-swift-proxy-server
      name: swift-proxy-server
      ports:
      - containerPort: 9292
    id: swift-1
    version: v1beta1
id: swift
labels:
  name: keystone-master
